# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-14 10:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20161014_1016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='site_id',
        ),
        migrations.RemoveField(
            model_name='item',
            name='type_ch',
        ),
    ]
