# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-14 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_item_playlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='source',
            field=models.CharField(max_length=255, verbose_name=b'\xd0\x90\xd0\xb4\xd1\x80\xd0\xb5\xd1\x81 \xd0\xbf\xd0\xbe\xd1\x82\xd0\xbe\xd0\xba\xd0\xb0'),
        ),
    ]
